name: cofi_env
channels:
  - conda-forge
  - defaults
  - gimli
dependencies:
  - python=3.10
  - jupyterlab>=3
  - matplotlib>=3.5.0
  - nodejs>=12
  - pygimli
  - simpeg
  - pip
  - pip:
    - cofi>=0.1.2.dev7
    - cofi-espresso>=0.0.1.dev4
    - ipywidgets>=7.7.0
    - tqdm>=4.0
