name: cofi_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - jupyterlab>=3
  - matplotlib>=3.5.0
  - nodejs>=12
  - shapely
  - cython
  - cartopy
  - pip
  - pip:
    - cofi>=0.1.2.dev22
    - geo-espresso>=0.2.1.dev0 
    - ipywidgets>=7.7.0
    - tqdm>=4.0
    - seislib>=0.6.7
