name: esp_contrib
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.6
  - numpy>=1.20
  - scipy>=1.0.0
  - scikit-build
  - black
  - matplotlib
  - pytest
  - pip
  - pip:
    - pyyaml
    - versioningit==2.1.0
    - stdlib_list==0.8.0
    - pytest-json-report==2.0.4
