name: readthedocs
dependencies:
  - python=3.8
  - matplotlib>=3.5.0
  - scipy>=1.0.0
  - pip
  - pip:
    - sphinx-book-theme==0.3.2
    - sphinx-panels==0.6.0
    - sphinx-togglebutton==0.3.1
    - myst-nb==0.14.0
    - sphinx-gallery==0.10.1
    - pypandoc==1.7.5
    - sphinxcontrib-mermaid==0.7.1
    - sphinx-copybutton==0.5.0
