name: Routine check and update active list

on:
  workflow_dispatch:
  push:
    branches: main
  schedule:
    - cron: '42 0 * * *'      # daily at 0:42

jobs:
  gen_pkg_source:
    name: Generate package source
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get tags
        run: |
          git fetch --tags origin
          git describe

      - name: Install Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install -r envs/requirements_test.txt
          python -m pip install .

      - name: Install Espresso
        run: |
          python espresso_machine/build_package/build.py

      - name: Run tests and write results to contrib/active_problems.txt
        run: |
          python espresso_machine/build_package/test_examples.py

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "chore: update active list"
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          branch: routine_check
          title: "Update `contrib/active_problems.txt`"
          body: |
            Update `contrib/active_problems.txt`. 
            This pull request is auto-generated by [routine_check][1]

            [1]: https://github.com/inlab-geo/espresso/actions/workflows/routine_check.yml
          labels: |
            bug
            changes to existing problems
          delete-branch: true
